# Prod Profile
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=none

spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}

shortr.strategy=base62
